export enum ErrorCode {
    INTERNAL_ERROR = 'INTERNAL_ERROR',
    BAD_REQUEST = 'BAD_REQUEST',

    // Users
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    USER_INVALID = 'USER_INVALID',
    USER_EMAIL_EXISTS = 'USER_EMAIL_EXISTS',

    // Auth
    AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
    AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',

    // Tasks
    TASK_NOT_FOUND = 'TASK_NOT_FOUND',
    TASK_INVALID = 'TASK_INVALID',
}