export enum ErrorCode {
    INTERNAL_ERROR = 'INTERNAL_ERROR',
    BAD_REQUEST = 'BAD_REQUEST',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    USER_INVALID = 'USER_INVALID',
    USER_EMAIL_EXISTS = 'USER_EMAIL_EXISTS',
    AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
    AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
    AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
    TASK_NOT_FOUND = 'TASK_NOT_FOUND',
    TASK_INVALID = 'TASK_INVALID',
}