export enum ErrorCode {
    INTERNAL_ERROR = 'INTERNAL_ERROR',
    BAD_REQUEST = 'BAD_REQUEST',
    FORBIDDEN = 'FORBIDDEN',
    TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',

    // USER
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    USER_INVALID = 'USER_INVALID',
    USER_EMAIL_EXISTS = 'USER_EMAIL_EXISTS',

    // AUTH (authentication)
    AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
    AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
    AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
    AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',

    // AUTHORIZATION
    PERMISSION_DENIED = 'PERMISSION_DENIED',
    ROLE_NOT_ALLOWED = 'ROLE_NOT_ALLOWED',

    // GROUP
    GROUP_NOT_FOUND = 'GROUP_NOT_FOUND',
    GROUP_INVALID = 'GROUP_INVALID',
    GROUP_CREATE_FAILED = 'GROUP_CREATE_FAILED',
    GROUP_MEMBER_NOT_FOUND = 'GROUP_MEMBER_NOT_FOUND',
    GROUP_MEMBER_EXISTS = 'GROUP_MEMBER_EXISTS',

    // TASK
    TASK_NOT_FOUND = 'TASK_NOT_FOUND',
    TASK_INVALID = 'TASK_INVALID',

    // NOTIFICATION
    NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',

    // OTP
    OTP_INVALID = 'OTP_INVALID',
}